common: &common
  adapter: postgresql
  username: iot_printer_front
  password: 2much2do
  pool: 5
  timeout: 5000

development:
  <<: *common
  database: iot_printer_front_development

test:
  <<: *common
  database: iot_printer_front_test

production:
  <<: *common
  database: iot_printer_front_production

